### ISSUE TITLE
Implement Multihash as a struct

### ISSUE THREAD

**Issue by freitagbr** [freitagbr/cr-multihash#7]
`Multihash` is currently implemented as a `class`, but because a multihash is not a long-lived object, it might be better to be implemented as a `struct`.

**Comment by nfischer** [comment]
Sure. From [the docs](https://crystal-lang.org/docs/syntax_and_semantics/structs.html):

> So how do you choose between a struct and a class? The rule of thumb is that if no instance variable is ever reassigned, i.e. your type is immutable, you could use a struct, otherwise use a class.

If we allow Multihash instances to be mutable, we could get inconsistent state (e.g. a hash code for sha1 with a digest for sha256).

**Comment by freitagbr** [comment]
Right, it's better to have the Multihash instances to be immutable - another reason to use a struct.
