### ISSUE TITLE
Use symbols for function names?

### ISSUE THREAD

**Issue by freitagbr** [freitagbr/cr-multihash#8]
Crystal has [Symbols](https://crystal-lang.org/docs/syntax_and_semantics/literals/symbol.html) which are named constants backed by an `Int32` internally. Two references to a symbol with the same name are the same Symbol. In other words, `:my_symbol == :my_symbol`.

In order to save memory, it might make sense to change the hash functions maps from string -> int to symbol -> int:
```crystal
NAMES = {
    "identity" => 0x00,
    "sha-256" => 0x11,
    ...
}
```
to:
```crystal
NAMES = {
    :identity => 0x00,
    :sha_256 => 0x11,
    ...
}
```

**Comment by nfischer** [comment]
How will these symbols be exported from the multihash module? Are these accessed with `Multihash::identity`, `:identity`, `Multihash:::identity`, etc.? I think these need to be part of the module API.

**Comment by freitagbr** [comment]
Actually, symbols are global to the entire program, and are arbitrarily assigned an integer value at compile time. So, :sha_256 in our code is the same symbol as :sha_256 anywhere else in the program.

**Comment by nfischer** [comment]
@freitagbr I see that having potential namespace conflicts, right?

**Comment by freitagbr** [comment]
No, and this is the beauty of symbols. Unlike variables, where we care about the name _and_ the value, we only care about a symbol's name, and not its value. In fact we can't even determine or interact with the value, because it is assigned a random `Int32` value by the compiler.  And because we can't change the value ourselves, there's nothing to conflict.

**Comment by nfischer** [comment]
Hmmm that makes sense. If you can't define them, then you can't define them to different things. Symbols sound like the way to go then!
